name: workout_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  hydrated_bloc: ^8.1.0
  path_provider: ^2.0.11
  flutter_lorem: ^2.0.0
  json_annotation: ^4.0.0
  shared_preferences: ^2.0.15
  flutter_cache_manager: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  mocktail: ^0.2.0
  bloc_test: ^9.1.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/exercises/
